# Base paths
PREFIX=$(DESTDIR)/usr/local
CONFDIR=$(DESTDIR)/etc
INITDIR=$(DESTDIR)/etc/init.d
LIBDIR=$(DESTDIR)/var/lib
LOGDIR=$(DESTDIR)/var/log
RUNDIR=$(DESTDIR)/var/run
SRVDIR=$(DESTDIR)/srv
USRLIBDIR=$(DESTDIR)/usr/local/lib
BUILDPKG=0
PERL=/usr/bin/perl
